### ISSUE TITLE
Crash on startup Minecraft 1.20.1 (Forge 47.2.0)

### ISSUE THREAD

**Issue by UnderPixel1475** [nvb-uy/Eldritch_End#10]
The mod is always crashing and giving a error during mod loading, with this message that shows on the screen.

![Screenshot_1](https://github.com/nvb-uy/Eldritch_End/assets/124472837/faa6be17-46d3-4c5c-91b1-7e1be316a57b)

However, I have all the mod's depedencies, meaning I have necromicon 1.3.0, azurelib and even Connector, Connector Extras and the Forgified Fabric API installed, see my modlist .txt file attached below and a screenshot to show that I have the Forgified Fabric API installed.

![Screenshot_2](https://github.com/nvb-uy/Eldritch_End/assets/124472837/91ed1599-180c-41bf-b812-0b1ec96c6888)

[modlist.txt](https://github.com/nvb-uy/Eldritch_End/files/13806281/modlist.txt)

I also tried to downgrade the mod to it's 0.2.12 version and it didn't work.

See the debug.log and the crash-report .txt files below.

[crash-2024-01-01_20.07.14-fml.txt](https://github.com/nvb-uy/Eldritch_End/files/13806292/crash-2024-01-01_20.07.14-fml.txt)

[debug.log](https://github.com/nvb-uy/Eldritch_End/files/13806293/debug.log)

**Comment by nvb-uy** [comment]
If you are on forge then install necronomicon forge and azurelib forge. Your error is because the mods aren’t being detected by forge, the cause is not eldritch end, you are just missing those 2 mods as the error clearly states. Downgrading won’t help, because the issue isn’t EE directly

**Comment by UnderPixel1475** [comment]
Wow, that was pretty fast, props to you for always looking-out for issues regarding the mod. Did I download the wrong versions of azurelib and necronomicon then? Because, if you check my modlist, I have both of those depedencies, I directly installed them through Prism Launcher. Do I need to manually add the .jar files for azurelib and necronomicon?

**Comment by nvb-uy** [comment]
Then prism installed it wrong somehow, because the error shows that those mods weren’t loaded, meaning they’re either missing, disabled, or from another loader. Make sure you install Necronomicon Forge and AzureLib Forge for MC 1.20.1

Try ATLauncher, it’s my personal go-to and never had issues with it, alternatively, Modrinth Launcher is cool too

**Comment by UnderPixel1475** [comment]
ATLauncher huh? Have heard of it before, I believe I can import my modpacks into it? Also, I am not really sure, I just don't know what's happening, I have just manually downloaded and hand-picked the forge versions of azurelib and Necronomicon and made sure they were on 1.20.1 and also made sure that Necronomicon was on 1.3.0. It just keeps crashing and giving me the same error during mod loading, is it the issue really that it's missing the dependencies? I have them installed and everything else

**Comment by GwydionPwyll** [comment]
Had the same error: I had to downgrade Oculus from its most recent update and everything loaded just fine (seems to be falsely flagging Eldritch End as the problem even though the dependencies were installed).

**Comment by UnderPixel1475** [comment]
Truly a Minecraft moment, thanks so much, will downgrade Oculus then, might I ask, which specific version of Oculus you downgraded to?

**Comment by GwydionPwyll** [comment]
> Truly a Minecraft moment, thanks so much, will downgrade Oculus then, might I ask, which specific version of Oculus you downgraded to?

Looks like 1.6.13 (without the a).

**Comment by UnderPixel1475** [comment]
I did that and now, my Minecraft doesn't even give me a crash-report .txt file or a message anymore, it just closes on itself while trying to load up. Great. But it's now clear that the problem isn't with EE so, I will close this issue, thanks so much for trying to help me though.
