### ISSUE TITLE
REI breaking the corruption tooltip

### ISSUE THREAD

**Issue by Yunogugu** [nvb-uy/Eldritch_End#11]
Hello, 
This may be an Problem on my Side but i didnt find anything regarding that so i am just asking hopeing for an answer!
What could be the problem?
![image](https://github.com/nvb-uy/Eldritch_End/assets/156345486/a3b53125-8074-42af-8e37-3d5cd258563a)

**Comment by nvb-uy** [comment]
This seems to be an issue caused by REI when there's favorites. It's not really an issue from my mod because all I do is call the render item tooltip method, so it's REI breaking it.

Make an issue on REI's tracker

**Comment by Yunogugu** [comment]
May i ask if u recreated it?
Just so i can be sure ^^

**Comment by nvb-uy** [comment]
I can't reproduce it but i've gotten reports from this happening with REI. It doesn't seem to happen with EMI or JEI.
