### ISSUE TITLE
Forge 1.20.1 47.2.19 eldritch end keeps crashing 

### ISSUE THREAD

**Issue by jojofenin99** [nvb-uy/Eldritch_End#15]
here are the logs:
[crash-2024-02-23_13.35.10-client.txt](https://github.com/nvb-uy/Eldritch_End/files/14389685/crash-2024-02-23_13.35.10-client.txt)
[latest.log](https://github.com/nvb-uy/Eldritch_End/files/14389687/latest.log)

**Comment by Apocalyptichobo** [comment]
I am getting the same thing after updating to the newest version of the Connector

**Comment by nvb-uy** [comment]
Connector Extras has an issue loading AzurelLib, please downgrade it
