### ISSUE TITLE
BMC4 [FORGE] v26 - Eldritch End causing crashes?

### ISSUE THREAD

**Issue by ahdeeluna** [nvb-uy/Eldritch_End#16]
Could not execute entrypoint stage 'main' due to errors, provided by 'eldritch_end'!

I'm using the better minecraft modpack and if I have Eldritch End enabled it causes my game to crash while loading. I saw someone mention in another issue that the connector or azurelib may be causing the problems with it but I have tried with Azure lib disabled and it was still crashing rather than loading through and telling me that a mod was missing. I had done the same with Sinytra Connector and anytime Eldritch End was disabled I didn't get any crashes. Only when Eldritch End was enabled is when I dealt with crashing.

 
[crash-2024-03-13_15.28.44-client.txt](https://github.com/nvb-uy/Eldritch_End/files/14594537/crash-2024-03-13_15.28.44-client.txt)

**Comment by nvb-uy** [comment]
Please don't update all mods on a modpack, things like these can happen.

The issue is due to Connector Extras, the developer will push a fix soon. In the meantime, downgrade it a few versions. (2-3)
