### ISSUE TITLE
Crash, mod incompatibility ?

### ISSUE THREAD

**Issue by Crankonator** [nvb-uy/Eldritch_End#17]
Trying to use the search function in SOL Onion(Creative core) in-game config editor crashes when eldritch end is present

forge - 47.2.18
eldritch - 0.2.31

[crash-2024-03-17_18.02.52-client.txt](https://github.com/nvb-uy/Eldritch_End/files/14628207/crash-2024-03-17_18.02.52-client.txt)

**Comment by nvb-uy** [comment]
looks like I can fix this from my end, i'll look into it

**Comment by nvb-uy** [comment]
fixed in 0.3.0 indev
