### ISSUE TITLE
Sinytra Connector Breakage because of issue #24

### ISSUE THREAD

**Issue by Bliss-tbh** [nvb-uy/Eldritch_End#25]
Sinytra Connector sees Elditch End forge as a fabric mod which leads to some breaky stuff happening such as the world freezing and crashing and excessive ram usage leading to out of memory errors...

**Comment by nvb-uy** [comment]
Ummm, Eldritch End IS a fabric mod... what?

**Comment by Bliss-tbh** [comment]
nvm im kinda dumb I just realised this was caused by a diff mod
