### ISSUE TITLE
Quark! - This mod somehow removed corruption details in the inventory

### ISSUE THREAD

**Issue by JAugustineFlory** [nvb-uy/Eldritch_End#30]
![Screenshot 2024-07-31 102447](https://github.com/user-attachments/assets/0909b722-7430-48b8-9265-dd593e171ba6)

There are a few more mods installed, but it only happened after downloading quark.
Here is the modlist, just in case:
.
.
.
.
.
.
.
![Screenshot 2024-07-31 102657](https://github.com/user-attachments/assets/003a97b6-b7df-4bef-97b4-3b6a78dc60c8)
![Screenshot 2024-07-31 102646](https://github.com/user-attachments/assets/acc8b3c1-c3b9-4d78-a564-85a2a89df9b4)
![Screenshot 2024-07-31 102634](https://github.com/user-attachments/assets/c62bbc15-9932-42b8-92d6-6de618d56f57)

**Comment by nvb-uy** [comment]
Please make an issue on Quark’s issue tracker. I use the native renderItemTooltip method, which Quark seems to be breaking.

**Comment by JAugustineFlory** [comment]
It was not Quark
