### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by kaairu** [nvb-uy/Eldritch_End#4]
game crashes only when eldritch end is present. possible mod conflict, works fine with azurelib but with eldritch end on it'll crash

https://mclo.gs/9Kq2YKR

**Comment by nvb-uy** [comment]
Try downgrading back to 0.2.12

**Comment by kaairu** [comment]
still occurs https://mclo.gs/HUYQOPY

**Comment by nvb-uy** [comment]
try without the essential mod

**Comment by nvb-uy** [comment]
if possible send a crash log instead of latest

**Comment by kaairu** [comment]
still happens w/out essentials. https://mclo.gs/Tb8FjXi 

only provides a latest.log no crash report

**Comment by kaairu** [comment]
connector beta 27 seems to fix this somehow.
