### ISSUE TITLE
[Forge 1.20.1] FORGE won't load the mod

### ISSUE THREAD

**Issue by aguzzfw** [nvb-uy/Eldritch_End#9]
When using: Eldritch_End-FORGE-MC1.20.1-0.2.30, azurelib-forge-1.20.1-2.0.18, Necronomicon-Forge-1.3.0, and several other mods...

Forge won't load the "Eldritch End" mod. It's not on the mods list inside the game, and the logs don't show any error or hint that the mod loader has loaded correctly the mod; it doesn't even mention it. I'm not sure what more info I could provide, or if maybe, I'm doing something wrong.

I'll attach the latest log, which mentions all mods used.

[latest.log](https://github.com/nvb-uy/Eldritch_End/files/13801929/latest.log)

**Comment by nvb-uy** [comment]
You need Connector, Connector Extras and Forgified Fabric API
